@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Mon Dec 21 13:09:31 +0800 2020
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim SingleCPU_tb_behav -key {Behavioral:sim_1:Functional:SingleCPU_tb} -tclbatch SingleCPU_tb.tcl -view C:/Users/lerogo/Desktop/组原实验/hhl4/singlemips32cpu/SingleCPU_tb_behav.wcfg -log simulate.log"
call xsim  SingleCPU_tb_behav -key {Behavioral:sim_1:Functional:SingleCPU_tb} -tclbatch SingleCPU_tb.tcl -view C:/Users/lerogo/Desktop/组原实验/hhl4/singlemips32cpu/SingleCPU_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
